services:
  nginx:
    container_name: nginx
    build: 
      context: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress
    restart: always
    networks:
      - inception

  mariadb:
    container_name: mariadb
    build: 
      context: ./requirements/mariadb
    volumes:
      - db:/var/lib/mysql
    env_file:
      - .env
    restart: always
    networks:
      - inception

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
    env_file:
      - .env
    restart: always
    networks:
      - inception

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/hyeonwch/data/wordpress
      o: bind
  db:
    driver: local
    driver_opts:
      type: none
      device: /home/hyeonwch/data/mariadb
      o: bind

networks:
  inception:
    name: inception
    driver: bridge